### PR TITLE
Remove unnecessary allocations in lexer

### PR DESCRIPTION
**Pull request by ocboogie**

### CODE REVIEW

**Comment by Wafelack** [comment]
Accepted

**Comment by ocboogie** [comment]
I know you already merged it, but here's some proof:
```rust
use alloc_counter::count_alloc;
use alloc_counter::AllocCounterSystem;

#[global_allocator]
static A: AllocCounterSystem = AllocCounterSystem;

fn main() {
    let test = "hello world";

    let (counts, _) = count_alloc(|| {
        test.chars().collect::<Vec<char>>()[5];
    });
    println!(
        "collect:
        Allocations: {}
        Reallocations: {}
        Deallocations: {}",
        counts.0, counts.1, counts.2
    );
    let (counts, _) = count_alloc(|| {
        test.chars().nth(5).unwrap();
    });
    println!(
        "nth:
        Allocations: {}
        Reallocations: {}
        Deallocations: {}",
        counts.0, counts.1, counts.2
    );
}
```
Output:
```
collect:
        Allocations: 1
        Reallocations: 2
        Deallocations: 1
nth:
        Allocations: 0
        Reallocations: 0
        Deallocations: 0
```

**Comment by Wafelack** [comment]
Oh nice, significantly improving it, thx.

I benched after it on Ackermann(3,3) and i passed from 220ms before to 150ms now, thx !

**Comment by Wafelack** [comment]
I have another question, is .to_owned() more performant that .clone() ?

**Comment by Wafelack** [comment]
E.g on a vec

**Comment by ocboogie** [comment]
I think it's the same:
```rust
extern crate test;

use test::Bencher;

#[bench]
fn to_owned(b: &mut Bencher) {
    let foo = (0..1000).collect::<Vec<_>>();
    b.iter(|| foo.to_owned());
}

#[bench]
fn clone(b: &mut Bencher) {
    let foo = (0..1000).collect::<Vec<_>>();
    b.iter(|| foo.clone());
}
```
output:
```
test clone    ... bench:          90 ns/iter (+/- 11)
test to_owned ... bench:          91 ns/iter (+/- 20)
```

**Comment by ocboogie** [comment]
I would do `clone` because that's usually the standard, but I don't think it matters too much.

**Comment by Wafelack** [comment]
Okk thank you !

**Pull request merged**
